import commonmark
import lark


def markdown_to_tree(mardown_ast):
    """Convert markdown AST to tree

    Args:
        mardown_ast (commonmark.node.Node): Parsed markdown AST. Usually
            generated by commonmark.Parser().parse(text).

    Returns:
        lark.Tree: Tree representation of markdown's AST.
    """
    pass


class MarkdownTransformer(lark.Transformer):
    """Convert MarkdownTree to SphinxNodeTree."""
    pass


def tree_to_sphinx_node(tree):
    """Convert tree representation to sphinx node API.

    Args:
        tree (lark.Tree): Tree represntation to sphinx node API.
    """
    raise NotImplementedError